import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import { PageTransition } from "@/components/ui/PageTransition";
import { LenisProvider } from "@/components/layout/LenisProvider";
import { ScrollHUD } from "@/components/ui/ScrollHUD";
import { ThemeGlitchFilter } from "@/components/ui/ThemeGlitchFilter";
import { BASE_URL, SITE_NAME, SITE_DESCRIPTION } from "@/lib/constants";
import { organizationJsonLd } from "@/lib/jsonld";
import "./globals.css";

// CodeNewRoman Nerd Font (Propo variant) — proportional Nerd Fonts patch
// designed for body prose. We subset to Latin + Latin-1 + general
// punctuation + box-drawing only (nerd-icon glyphs dropped), which cuts
// each weight from ~6.5MB down to ~45KB woff2. Korean characters fall
// back per-glyph to Pretendard via the CSS chain in globals.css.
const codeNewRoman = localFont({
  src: [
    {
      path: "./fonts/CodeNewRomanPropo-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/CodeNewRomanPropo-Italic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/CodeNewRomanPropo-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-code-new-roman",
  display: "swap",
  preload: true,
  fallback: ["Pretendard Variable", "Pretendard", "system-ui", "sans-serif"],
});

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#000000" },
  ],
};

export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),
  title: {
    template: `%s — ${SITE_NAME}`,
    default: SITE_NAME,
  },
  description: SITE_DESCRIPTION,
  keywords: ["개발", "프로그래밍", "보안", "네트워크", "시스템", "블로그"],
  authors: [{ name: SITE_NAME }],
  creator: SITE_NAME,
  openGraph: {
    type: "website",
    locale: "ko_KR",
    url: BASE_URL,
    siteName: SITE_NAME,
    title: SITE_NAME,
    description: SITE_DESCRIPTION,
    // OG image is auto-generated by opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: SITE_NAME,
    description: SITE_DESCRIPTION,
  },
  alternates: {
    canonical: "/",
    types: {
      "application/rss+xml": "/feed.xml",
    },
  },
  icons: {
    icon: "/favicon.ico",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large" as const,
      "max-snippet": -1,
    },
  },
  other: {
    "naver-site-verification": "23fa137694f4b93ebce392d3519c524e903badee",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={codeNewRoman.variable} suppressHydrationWarning>
      <head>
        <link
          rel="preload"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable.min.css"
          as="style"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable.min.css"
        />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                if (localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                  document.documentElement.classList.add('dark');
                } else {
                  document.documentElement.classList.remove('dark');
                }
              } catch (_) {}
            `,
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(organizationJsonLd()),
          }}
        />
      </head>
      <body className="min-h-screen bg-bg text-black font-[family-name:var(--font-sans)] transition-colors duration-500">
        <ThemeGlitchFilter />
        <LenisProvider>
          <ScrollHUD />
          <PageTransition />
          {children}
        </LenisProvider>
      </body>
    </html>
  );
}
